apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appName
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: appName
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60